spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3333/mail
    username: root
    password: 123
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
# Mail Setting
  mail:
    host: smtp.gmail.com # 1
    port: 587 # 2
    username: "dbwjdghman93" # 3
    password: "zqza cmyf elhx oelv" # 4
    properties:
      mail:
        smtp:
          auth: true # 5
          timeout: 5000 # 6
          starttls:
            enable: true # 7