spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/test
    username: root
    password: 123
    driver-class-name: org.mariadb.jdbc.Driver

  ## JPA setting
  jpa:
    hibernate:
      ddl-auto: update

