spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/test
    username: root
    password: 123

mybatis:
  mapper-locations: classpath:mapper/**/*.xml


